defmodule DemocoruwtfWeb.CardLive.Card do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Phoenix.LiveComponent
  use Phoenix.HTML

  alias Democoruwtf.Cards
  alias Democoruwtf.Cards.Card

  @impl true
  def render(assigns) do
    ~H"""
    <div  class={"block mx-12 p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 space-x-4 space-y-4 my-8"}>
        <div class="text-center mx-8 "><%= @card.content %></div>
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 text-center capitalize" ><%= @card.state %></h5>

        <div class="flex justify-center items-center flex-row space-x-5">
          <span class="inline-flex items-center font-medium text-blue-600 dark:text-blue-500 hover:underline"><%= live_patch "Edit", to: DemocoruwtfWeb.Router.Helpers.card_index_path(@socket, :edit, @card) %></span>
          <span class="inline-flex items-center font-medium text-red-600 dark:text-red-600 hover:underline"><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: @card.id, data: [confirm: "Are you sure?"] %></span>
        </div>
        </div>
    """
  end
end
